### ISSUE TITLE
Bug: SteamVR Float & Vector2 Actions Subscribed to Incorrect Event

### ISSUE THREAD

**Issue by SamuelACook** [ExtendRealityLtd/Tilia.SDK.SteamVR.Unity#47]
### Environment

* Code source: C#
* Code version: NET 4.x
* Platform version: Unity 2019.4.31f1
* 3rd party dependencies: NA

### Steps to reproduce

1. Add SteamVR Bindings for float or Vector2
2. Add SteamVR float or Vector2 Actions & Behavior Components to GameObject
3. Start the Game and press the input button to adjust the float or vector2 value
4. Notice the value can never be set back to 0, the value will stick to the previous value before 0

### Expected behavior

SteamVRBehaviorFloatAction and SteamVRBehaviorVector2Action to be updated on value change, whether it be 0 or 1 or .5f.

### Current behavior

Will only update the value on everything except 0. Currently, the Behavior script components subscribe to the onAxis event, "Unity event that fires whenever the action's value has been updated and is non-zero". Instead, it should be subscribed to onUpdate which is "Fires whenever the action's value has been updated."

![rider64_DeVBMtr3up](https://user-images.githubusercontent.com/11304433/171489488-fff5869d-d902-4c7b-bd99-78e92e8c7ece.png)

**Comment by SamuelACook** [comment]
Would it be preferable if I set up a pull request to fix this bug?

**Comment by thestonefox** [comment]
sure if you want, make sure you follow the contributing guidelines and ensure the git messages, etc are all adhering.

**Comment by thestonefox** [comment]
does `onUpdate` fire every frame? and therefore does `onChange` make more sense (and does onChange also report a 0 value?)

**Comment by SamuelACook** [comment]
Not sure, I'll do some tests to confirm and report back. I think you are right that onUpdate might be firing the event even when it doesn't change value.

**Comment by SamuelACook** [comment]
> does `onUpdate` fire every frame? and therefore does `onChange` make more sense (and does onChange also report a 0 value?)

Your right, `onChange `would be better. It calls the event when the value changes, including 0. `onUpdate `gets called every frame, not just when the value changes.
